version: '3'
services:
    mysql:
        image: mysql:5.7.20
        ports:
            - "33060:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=1234"
            - "MYSQL_DATABASE=rebel_db"